# This docker-compose yml describe the services to run locally
version: '2'

# Defines the services
services:

  # Test image (packages, services, scripts)
  test-image:
    image: bandsintown/alpine-test:${VERSION}
    command: dockerize -wait http://consul:8500 -timeout 10s bats /tests/image
    depends_on:
      - consul
    environment:
      - VERSION=${VERSION}
      - CONSUL_ADDRESS=consul:8500
      - CONSUL_SERF_ADDRESS=consul:8301

  # Tests with only one DNS Nameserver and Search Domain
  test-dns:
    image: bandsintown/alpine-test:${VERSION}
    command: bats /tests/dnsmasq/01-resolve_dns.bats
    dns: 8.8.4.4
    dns_search: 10.0.0.1.xip.io
    environment:
      - VERSION=${VERSION}

  # Tests with Multiple DNS Nameserver and Search Domain
  test-dns-multiple:
    image: bandsintown/alpine-test:${VERSION}
    command: bats /tests/dnsmasq/02-resolve_dns_multiple.bats
    dns:
     - 8.8.4.4
     - 8.8.8.8
    dns_search:
      - google.com
      - video.google.com
    environment:
      - VERSION=${VERSION}

  # Tests for consul template
  test-consul-template:
    image: bandsintown/alpine-test:${VERSION}
    command: dockerize -wait http://consul:8500 -timeout 10s bats /tests/consul-template
    depends_on:
      - consul
    environment:
      - DISABLE_CONSUL_TEMPLATE=true
      - CONSUL_ADDRESS=consul:8500
      - CONSUL_SERF_ADDRESS=consul:8301
      - VERSION=${VERSION}

  # Tests for consul managed by S6
  test-consul:
    image: bandsintown/alpine-test:${VERSION}
    command: dockerize -wait http://consul:8500 -timeout 10s bats /tests/consul
    depends_on:
      - consul
    environment:
      - DISABLE_CONSUL_TEMPLATE=true
      - ENABLE_CONSUL=true
      - CONSUL_ADDRESS=consul:8500
      - CONSUL_SERF_ADDRESS=consul:8301
      - VERSION=${VERSION}

  # Consul
  consul:
    image: consul
    command: "agent -dev -client 0.0.0.0 -ui"
    ports:
      - 8500
      - 8600
      - 8301
    environment:
      - CONSUL_BIND_INTERFACE=eth0

    # We disable the log in order to increase lisibility in CI
    logging:
      driver: "none"